DROP TABLE "config";
CREATE TABLE "config" (
  "id" NUMBER(20) VISIBLE NOT NULL ,
  "nodeid" NUMBER(20) VISIBLE NOT NULL ,
  "comment" VARCHAR2(2048 BYTE) VISIBLE NOT NULL ,
  "data" CLOB VISIBLE NOT NULL ,
  "createtime" VARCHAR2(256 BYTE) VISIBLE NOT NULL ,
  "status" NUMBER(1) VISIBLE DEFAULT 0   NOT NULL
)
NOLOGGING
NOCOMPRESS
NOCACHE;

ALTER TABLE "config" ADD CHECK ("id" IS NOT NULL);
ALTER TABLE "config" ADD CHECK ("nodeid" IS NOT NULL);
ALTER TABLE "config" ADD CHECK ("comment" IS NOT NULL);
ALTER TABLE "config" ADD CHECK ("data" IS NOT NULL);
ALTER TABLE "config" ADD CHECK ("createtime" IS NOT NULL);
ALTER TABLE "config" ADD CHECK ("status" IS NOT NULL);

ALTER TABLE "config" ADD PRIMARY KEY ("id");
