DROP TABLE "history";
CREATE TABLE "history" (
  "id" NUMBER(20) VISIBLE NOT NULL ,
  "userid" NUMBER(20) VISIBLE NOT NULL,
  "name" VARCHAR2(256 BYTE) VISIBLE NOT NULL,
  "action" VARCHAR2(256 BYTE) VISIBLE NOT NULL,
  "comment" CLOB VISIBLE NOT NULL,
  "timestamp" VARCHAR2(256 BYTE) VISIBLE NOT NULL
)
NOLOGGING
NOCOMPRESS
NOCACHE;

ALTER TABLE "history" ADD CHECK ("id" IS NOT NULL);
ALTER TABLE "history" ADD CHECK ("userid" IS NOT NULL);
ALTER TABLE "history" ADD CHECK ("name" IS NOT NULL);
ALTER TABLE "history" ADD CHECK ("action" IS NOT NULL);
ALTER TABLE "history" ADD CHECK ("comment" IS NOT NULL);
ALTER TABLE "history" ADD CHECK ("timestamp" IS NOT NULL);

ALTER TABLE "history" ADD PRIMARY KEY ("id");
