DROP TABLE "warn";
CREATE TABLE "warn" (
  "id" NUMBER(20) VISIBLE NOT NULL ,
  "nodeid" NUMBER(20) VISIBLE NOT NULL ,
  "userid" NUMBER(20) VISIBLE ,
  "errcode" VARCHAR2(256 BYTE) VISIBLE NOT NULL ,
  "comment" VARCHAR2(2048 BYTE) VISIBLE NOT NULL ,
  "timestamp" VARCHAR2(256 BYTE) VISIBLE NOT NULL ,
  "explain" VARCHAR2(2048 BYTE) VISIBLE ,
  "dispose" VARCHAR2(256 BYTE) VISIBLE NOT NULL
)
NOLOGGING
NOCOMPRESS
NOCACHE;

ALTER TABLE "warn" ADD CHECK ("id" IS NOT NULL);
ALTER TABLE "warn" ADD CHECK ("nodeid" IS NOT NULL);
ALTER TABLE "warn" ADD CHECK ("errcode" IS NOT NULL);
ALTER TABLE "warn" ADD CHECK ("comment" IS NOT NULL);
ALTER TABLE "warn" ADD CHECK ("timestamp" IS NOT NULL);
ALTER TABLE "warn" ADD CHECK ("dispose" IS NOT NULL);

ALTER TABLE "warn" ADD PRIMARY KEY ("id");

INSERT INTO "warn" VALUES ('1', '2', '1', 'AA', '错误的文件', '2018-04-10 06:30:50', '11111', 'ignore');
